<?php

/**
 * Placeholder list of Philippine cities, used to power the type-ahead
 * "City" field on participant registration (resources/views/auth/register.blade.php).
 *
 * Not exhaustive — covers cities but not municipalities. The field still
 * accepts free text, so a participant whose city isn't listed here can just
 * type it; this list only exists to reduce typos for the common case.
 *
 * TODO: Replace with a proper PSGC (Philippine Standard Geographic Code)
 * dataset if the city needs to drive region-scoping the way "agency" does.
 */
return [
    'list' => [
        'Alaminos, Pangasinan',
        'Angeles, Pampanga',
        'Antipolo, Rizal',
        'Bacolod, Negros Occidental',
        'Bacoor, Cavite',
        'Bago, Negros Occidental',
        'Baguio, Benguet',
        'Bais, Negros Oriental',
        'Balanga, Bataan',
        'Batac, Ilocos Norte',
        'Batangas City, Batangas',
        'Bayawan, Negros Oriental',
        'Baybay, Leyte',
        'Bayugan, Agusan del Sur',
        'Biñan, Laguna',
        'Bislig, Surigao del Sur',
        'Bogo, Cebu',
        'Borongan, Eastern Samar',
        'Butuan, Agusan del Norte',
        'Cabadbaran, Agusan del Norte',
        'Cabanatuan, Nueva Ecija',
        'Cabuyao, Laguna',
        'Cadiz, Negros Occidental',
        'Cagayan de Oro, Misamis Oriental',
        'Calamba, Laguna',
        'Calapan, Oriental Mindoro',
        'Calbayog, Samar',
        'Caloocan, Metro Manila',
        'Candon, Ilocos Sur',
        'Canlaon, Negros Oriental',
        'Carcar, Cebu',
        'Catbalogan, Samar',
        'Cauayan, Isabela',
        'Cebu City, Cebu',
        'Cotabato City, Maguindanao del Norte',
        'Dagupan, Pangasinan',
        'Danao, Cebu',
        'Dapitan, Zamboanga del Norte',
        'Dasmariñas, Cavite',
        'Davao City, Davao del Sur',
        'Digos, Davao del Sur',
        'Dipolog, Zamboanga del Norte',
        'Dumaguete, Negros Oriental',
        'El Salvador, Misamis Oriental',
        'Escalante, Negros Occidental',
        'Gapan, Nueva Ecija',
        'General Santos, South Cotabato',
        'General Trias, Cavite',
        'Gingoog, Misamis Oriental',
        'Guihulngan, Negros Oriental',
        'Himamaylan, Negros Occidental',
        'Iligan, Lanao del Norte',
        'Iloilo City, Iloilo',
        'Imus, Cavite',
        'Iriga, Camarines Sur',
        'Isabela, Basilan',
        'Kabankalan, Negros Occidental',
        'Kidapawan, Cotabato',
        'Koronadal, South Cotabato',
        'La Carlota, Negros Occidental',
        'Lamitan, Basilan',
        'Laoag, Ilocos Norte',
        'Lapu-Lapu, Cebu',
        'Las Piñas, Metro Manila',
        'Legazpi, Albay',
        'Ligao, Albay',
        'Lipa, Batangas',
        'Lucena, Quezon',
        'Maasin, Southern Leyte',
        'Mabalacat, Pampanga',
        'Makati, Metro Manila',
        'Malabon, Metro Manila',
        'Malaybalay, Bukidnon',
        'Malolos, Bulacan',
        'Mandaluyong, Metro Manila',
        'Mandaue, Cebu',
        'Manila, Metro Manila',
        'Marawi, Lanao del Sur',
        'Marikina, Metro Manila',
        'Masbate City, Masbate',
        'Mati, Davao Oriental',
        'Meycauayan, Bulacan',
        'Muntinlupa, Metro Manila',
        'Naga, Camarines Sur',
        'Naga, Cebu',
        'Navotas, Metro Manila',
        'Olongapo, Zambales',
        'Ormoc, Leyte',
        'Oroquieta, Misamis Occidental',
        'Ozamiz, Misamis Occidental',
        'Pagadian, Zamboanga del Sur',
        'Palayan, Nueva Ecija',
        'Panabo, Davao del Norte',
        'Parañaque, Metro Manila',
        'Pasay, Metro Manila',
        'Pasig, Metro Manila',
        'Passi, Iloilo',
        'Pateros, Metro Manila',
        'Puerto Princesa, Palawan',
        'Quezon City, Metro Manila',
        'Roxas City, Capiz',
        'Sagay, Negros Occidental',
        'Samal, Davao del Norte',
        'San Carlos, Negros Occidental',
        'San Carlos, Pangasinan',
        'San Fernando, La Union',
        'San Fernando, Pampanga',
        'San Jose, Nueva Ecija',
        'San Jose del Monte, Bulacan',
        'San Juan, Metro Manila',
        'San Pablo, Laguna',
        'San Pedro, Laguna',
        'Santa Rosa, Laguna',
        'Santiago, Isabela',
        'Silay, Negros Occidental',
        'Sipalay, Negros Occidental',
        'Sorsogon City, Sorsogon',
        'Surigao City, Surigao del Norte',
        'Tabaco, Albay',
        'Tacloban, Leyte',
        'Tacurong, Sultan Kudarat',
        'Tagaytay, Cavite',
        'Tagbilaran, Bohol',
        'Taguig, Metro Manila',
        'Tagum, Davao del Norte',
        'Talisay, Cebu',
        'Talisay, Negros Occidental',
        'Tanauan, Batangas',
        'Tandag, Surigao del Sur',
        'Tangub, Misamis Occidental',
        'Tarlac City, Tarlac',
        'Toledo, Cebu',
        'Trece Martires, Cavite',
        'Tuguegarao, Cagayan',
        'Urdaneta, Pangasinan',
        'Valencia, Bukidnon',
        'Valenzuela, Metro Manila',
        'Victorias, Negros Occidental',
        'Vigan, Ilocos Sur',
        'Zamboanga City, Zamboanga del Sur',
    ],
];
