<?php

/**
 * Placeholder OCD Regional Office list, used to scope regional admin accounts.
 *
 * TODO: Replace with data from a Region model/table if regions ever need
 * their own attributes (contact info, boundaries, etc).
 */
return [
    'list' => [
        'NCR',
        'CAR',
        'Region I',
        'Region II',
        'Region III',
        'Region IV-A',
        'MIMAROPA',
        'Region V',
        'Region VI',
        'Region VII',
        'Region VIII',
        'Region IX',
        'Region X',
        'Region XI',
        'Region XII',
        'Region XIII',
        'BARMM',
        'OCD Central',
    ],

    /**
     * Maps the "OCD Regional Office" option a participant picks at registration
     * (resources/views/auth/register.blade.php) to the matching entry in `list`
     * above, so participants can be scoped to a region the same way admins are.
     *
     * NIR isn't in `list` yet (no matching regional admin scope exists), so it's
     * left unmapped — those participants stay regionless until that's resolved.
     */
    'agency_map' => [
        'OCD-NCR: National Capital Region' => 'NCR',
        'OCD-CAR: Cordillera Administrative Region' => 'CAR',
        'OCD-Region I: Ilocos Region' => 'Region I',
        'OCD-Region II: Cagayan Valley' => 'Region II',
        'OCD-Region III: Central Luzon' => 'Region III',
        'OCD-Region IV-A: CALABARZON' => 'Region IV-A',
        'OCD-Region IV-B: MIMAROPA' => 'MIMAROPA',
        'OCD-Region V: Bicol Region' => 'Region V',
        'OCD-Region VI: Western Visayas' => 'Region VI',
        'OCD-Region VII: Central Visayas' => 'Region VII',
        'OCD-Region VIII: Eastern Visayas' => 'Region VIII',
        'OCD-Region IX: Zamboanga Peninsula' => 'Region IX',
        'OCD-Region X: Northern Mindanao' => 'Region X',
        'OCD-Region XI: Davao Region' => 'Region XI',
        'OCD-Region XII: SOCCSKSARGEN' => 'Region XII',
        'OCD-Region XIII: Caraga' => 'Region XIII',
    ],

    /**
     * Maps each entry in config/cities.php's list to the region it's in, so
     * picking a city on the registration page (resources/views/auth/register.blade.php)
     * can auto-fill the "Region" select below it. Participants can still
     * override the guess or type a city that isn't listed (region is then
     * left for them to pick manually).
     *
     * Negros Occidental/Oriental cities map to Region VI/VII rather than NIR,
     * matching agency_map above (NIR has no regional admin scope yet).
     * Isabela City, Basilan maps to Region IX (not BARMM) — it opted to stay
     * under Zamboanga Peninsula's administration rather than ARMM/BARMM.
     */
    'city_region_map' => [
        'Alaminos, Pangasinan' => 'Region I',
        'Angeles, Pampanga' => 'Region III',
        'Antipolo, Rizal' => 'Region IV-A',
        'Bacolod, Negros Occidental' => 'Region VI',
        'Bacoor, Cavite' => 'Region IV-A',
        'Bago, Negros Occidental' => 'Region VI',
        'Baguio, Benguet' => 'CAR',
        'Bais, Negros Oriental' => 'Region VII',
        'Balanga, Bataan' => 'Region III',
        'Batac, Ilocos Norte' => 'Region I',
        'Batangas City, Batangas' => 'Region IV-A',
        'Bayawan, Negros Oriental' => 'Region VII',
        'Baybay, Leyte' => 'Region VIII',
        'Bayugan, Agusan del Sur' => 'Region XIII',
        'Biñan, Laguna' => 'Region IV-A',
        'Bislig, Surigao del Sur' => 'Region XIII',
        'Bogo, Cebu' => 'Region VII',
        'Borongan, Eastern Samar' => 'Region VIII',
        'Butuan, Agusan del Norte' => 'Region XIII',
        'Cabadbaran, Agusan del Norte' => 'Region XIII',
        'Cabanatuan, Nueva Ecija' => 'Region III',
        'Cabuyao, Laguna' => 'Region IV-A',
        'Cadiz, Negros Occidental' => 'Region VI',
        'Cagayan de Oro, Misamis Oriental' => 'Region X',
        'Calamba, Laguna' => 'Region IV-A',
        'Calapan, Oriental Mindoro' => 'MIMAROPA',
        'Calbayog, Samar' => 'Region VIII',
        'Caloocan, Metro Manila' => 'NCR',
        'Candon, Ilocos Sur' => 'Region I',
        'Canlaon, Negros Oriental' => 'Region VII',
        'Carcar, Cebu' => 'Region VII',
        'Catbalogan, Samar' => 'Region VIII',
        'Cauayan, Isabela' => 'Region II',
        'Cebu City, Cebu' => 'Region VII',
        'Cotabato City, Maguindanao del Norte' => 'BARMM',
        'Dagupan, Pangasinan' => 'Region I',
        'Danao, Cebu' => 'Region VII',
        'Dapitan, Zamboanga del Norte' => 'Region IX',
        'Dasmariñas, Cavite' => 'Region IV-A',
        'Davao City, Davao del Sur' => 'Region XI',
        'Digos, Davao del Sur' => 'Region XI',
        'Dipolog, Zamboanga del Norte' => 'Region IX',
        'Dumaguete, Negros Oriental' => 'Region VII',
        'El Salvador, Misamis Oriental' => 'Region X',
        'Escalante, Negros Occidental' => 'Region VI',
        'Gapan, Nueva Ecija' => 'Region III',
        'General Santos, South Cotabato' => 'Region XII',
        'General Trias, Cavite' => 'Region IV-A',
        'Gingoog, Misamis Oriental' => 'Region X',
        'Guihulngan, Negros Oriental' => 'Region VII',
        'Himamaylan, Negros Occidental' => 'Region VI',
        'Iligan, Lanao del Norte' => 'Region X',
        'Iloilo City, Iloilo' => 'Region VI',
        'Imus, Cavite' => 'Region IV-A',
        'Iriga, Camarines Sur' => 'Region V',
        'Isabela, Basilan' => 'Region IX',
        'Kabankalan, Negros Occidental' => 'Region VI',
        'Kidapawan, Cotabato' => 'Region XII',
        'Koronadal, South Cotabato' => 'Region XII',
        'La Carlota, Negros Occidental' => 'Region VI',
        'Lamitan, Basilan' => 'BARMM',
        'Laoag, Ilocos Norte' => 'Region I',
        'Lapu-Lapu, Cebu' => 'Region VII',
        'Las Piñas, Metro Manila' => 'NCR',
        'Legazpi, Albay' => 'Region V',
        'Ligao, Albay' => 'Region V',
        'Lipa, Batangas' => 'Region IV-A',
        'Lucena, Quezon' => 'Region IV-A',
        'Maasin, Southern Leyte' => 'Region VIII',
        'Mabalacat, Pampanga' => 'Region III',
        'Makati, Metro Manila' => 'NCR',
        'Malabon, Metro Manila' => 'NCR',
        'Malaybalay, Bukidnon' => 'Region X',
        'Malolos, Bulacan' => 'Region III',
        'Mandaluyong, Metro Manila' => 'NCR',
        'Mandaue, Cebu' => 'Region VII',
        'Manila, Metro Manila' => 'NCR',
        'Marawi, Lanao del Sur' => 'BARMM',
        'Marikina, Metro Manila' => 'NCR',
        'Masbate City, Masbate' => 'Region V',
        'Mati, Davao Oriental' => 'Region XI',
        'Meycauayan, Bulacan' => 'Region III',
        'Muntinlupa, Metro Manila' => 'NCR',
        'Naga, Camarines Sur' => 'Region V',
        'Naga, Cebu' => 'Region VII',
        'Navotas, Metro Manila' => 'NCR',
        'Olongapo, Zambales' => 'Region III',
        'Ormoc, Leyte' => 'Region VIII',
        'Oroquieta, Misamis Occidental' => 'Region X',
        'Ozamiz, Misamis Occidental' => 'Region X',
        'Pagadian, Zamboanga del Sur' => 'Region IX',
        'Palayan, Nueva Ecija' => 'Region III',
        'Panabo, Davao del Norte' => 'Region XI',
        'Parañaque, Metro Manila' => 'NCR',
        'Pasay, Metro Manila' => 'NCR',
        'Pasig, Metro Manila' => 'NCR',
        'Passi, Iloilo' => 'Region VI',
        'Pateros, Metro Manila' => 'NCR',
        'Puerto Princesa, Palawan' => 'MIMAROPA',
        'Quezon City, Metro Manila' => 'NCR',
        'Roxas City, Capiz' => 'Region VI',
        'Sagay, Negros Occidental' => 'Region VI',
        'Samal, Davao del Norte' => 'Region XI',
        'San Carlos, Negros Occidental' => 'Region VI',
        'San Carlos, Pangasinan' => 'Region I',
        'San Fernando, La Union' => 'Region I',
        'San Fernando, Pampanga' => 'Region III',
        'San Jose, Nueva Ecija' => 'Region III',
        'San Jose del Monte, Bulacan' => 'Region III',
        'San Juan, Metro Manila' => 'NCR',
        'San Pablo, Laguna' => 'Region IV-A',
        'San Pedro, Laguna' => 'Region IV-A',
        'Santa Rosa, Laguna' => 'Region IV-A',
        'Santiago, Isabela' => 'Region II',
        'Silay, Negros Occidental' => 'Region VI',
        'Sipalay, Negros Occidental' => 'Region VI',
        'Sorsogon City, Sorsogon' => 'Region V',
        'Surigao City, Surigao del Norte' => 'Region XIII',
        'Tabaco, Albay' => 'Region V',
        'Tacloban, Leyte' => 'Region VIII',
        'Tacurong, Sultan Kudarat' => 'Region XII',
        'Tagaytay, Cavite' => 'Region IV-A',
        'Tagbilaran, Bohol' => 'Region VII',
        'Taguig, Metro Manila' => 'NCR',
        'Tagum, Davao del Norte' => 'Region XI',
        'Talisay, Cebu' => 'Region VII',
        'Talisay, Negros Occidental' => 'Region VI',
        'Tanauan, Batangas' => 'Region IV-A',
        'Tandag, Surigao del Sur' => 'Region XIII',
        'Tangub, Misamis Occidental' => 'Region X',
        'Tarlac City, Tarlac' => 'Region III',
        'Toledo, Cebu' => 'Region VII',
        'Trece Martires, Cavite' => 'Region IV-A',
        'Tuguegarao, Cagayan' => 'Region II',
        'Urdaneta, Pangasinan' => 'Region I',
        'Valencia, Bukidnon' => 'Region X',
        'Valenzuela, Metro Manila' => 'NCR',
        'Victorias, Negros Occidental' => 'Region VI',
        'Vigan, Ilocos Sur' => 'Region I',
        'Zamboanga City, Zamboanga del Sur' => 'Region IX',
    ],

    /**
     * Approximate [latitude, longitude] centre of each region, used by the
     * Training Graduates Map to plot trainings that weren't encoded with
     * their own coordinates.
     */
    'geo' => [
        'Region I' => [16.6159, 120.3166],
        'Region II' => [16.9754, 121.8107],
        'Region III' => [15.4828, 120.7120],
        'Region IV-A' => [14.1008, 121.0794],
        'MIMAROPA' => [12.4293, 121.0349],
        'Region V' => [13.4209, 123.4137],
        'Region VI' => [10.9971, 122.5711],
        'Region VII' => [10.0000, 123.6000],
        'Region VIII' => [11.4000, 124.9000],
        'Region IX' => [7.8383, 123.2968],
        'Region X' => [8.4822, 124.6472],
        'Region XI' => [7.0731, 125.6128],
        'Region XII' => [6.2707, 124.6857],
        'Region XIII' => [8.9475, 125.5406],
        'NCR' => [14.5995, 120.9842],
        'CAR' => [17.3513, 121.1719],
        'BARMM' => [7.2078, 124.2500],
        // Camp General Emilio Aguinaldo (OCD Central Office) is in Quezon
        // City/NCR — reusing NCR's coordinates rather than guessing a more
        // precise pin.
        'OCD Central' => [14.5995, 120.9842],
    ],
];
