<?php

/**
 * Digitized content of the OCD "TNA Tool for National and Regional DRRM
 * Council Members" PDF. Keep this in sync with the source PDF — do not
 * reword statements, since they are validated against verbatim on
 * submission. Facets are grouped by domain exactly as printed in the tool.
 */
return [

    'facets' => [
        [
            'domain' => 'Plan Formulation on DRRM',
            'items' => [
                'Development of plans, policies, guidelines, and protocols',
                'Environmental scanning',
                'Land use planning',
                'Development planning',
                'Budgeting and programming of activities for Disaster Risk Reduction and Management and/or Climate Change Adaptation and Mitigation',
                'Conduct of research on Disaster Risk Reduction and Management and/or Climate Change Adaptation and Mitigation',
                'Conduct of monitoring and evaluation of program results',
                'Review and updating of plans, policies, guidelines, and protocols',
            ],
        ],
        [
            'domain' => 'Disaster Risk Assessment',
            'items' => [
                'Demographic data analysis and assessment',
                'Risk Hazard Vulnerability Assessment',
                'Documentation, review, and analysis of past occurence',
                'Generation of scenarios and models',
                'Map development (hazard map, risk map, vulnerability map, etc)',
                'Development of risk assessment tools',
                'Projection of damage and loss estimates',
            ],
        ],
        [
            'domain' => 'Disaster and Climate-Resilient Infrastructure Standards',
            'items' => [
                'Development of designs and standards for building resilient facilities, infrastructures, transportation systems, and other disaster control measures',
                'Construction of facilities, infrastructures, transportations systems, and other disaster control measures',
                'Maintenance of facilities, infrastructures, transportation systems, and other control measures',
                'Assessment and inspection of facilities, infrastructures, transportation systems, and other disaster control measures',
                'Conduct of monitoring of compliance of stakeholders on agreed designs and standards',
            ],
        ],
        [
            'domain' => 'Science-Based Hazard Prediction and Risk Mitigation Systems',
            'items' => [
                'Conduct of science and evidence-based forecasting and prediction',
                'Conduct of real-time situation monitoring',
                'Development of parameters and indicators for early warning',
                'Development of monitoring and warning tools and instruments',
                'Analysis and interpretation of results of monitoring',
                'Establishment, repair, and maintenance of facilities for monitoring and early warning',
                'Development of situation monitoring reports',
                'Dissemination of results of situation monitoring to relevant stakeholders',
            ],
        ],
        [
            'domain' => 'Disaster Risk Financing and Insurance',
            'items' => [
                'Development of policies, guidelines, and standards for financial arrangement schemes',
                'Dissemination of policies, guidelines, and standards for financial arrangement schemes',
                'Processing of requests for availing of financial arrangements schemes',
                'Monitoring and reporting of utilization of financial arrangement schemes',
            ],
        ],
        [
            'domain' => 'DRRM and Climate Change Program Development and Implementation',
            'items' => [
                'Development of policies, guidelines, and standards',
                'Development and maintaining of Disaster Risk Reduction and Management plans',
                'Development, designing, and enhancement of programs/projects/activities for disaster preparedness',
                'Conduct of training needs assessment within the organization',
                'Development, designing, and enhancement of training course contents',
                'Implementation of training course as trainer, facilitator, or support staff',
                'Development of programs/projects/activities for preparedness to respond',
                'Monitoring and documentation of training progresses and achievements',
                'Evaluation of the results of training course and PIR',
                'Program/projects/activities implementation review',
            ],
        ],
        [
            'domain' => 'Organizational Preparedness and Resource Management',
            'items' => [
                'Formulation of contingency plans',
                'Development of public service continuity programs',
                'Logistical management of resources and equipment',
                'Logistical management of facilities',
                'Logistical management of organization',
                'Monitoring and evaluation of the implementation of logistics management protocols and procedures',
            ],
        ],
        [
            'domain' => 'Stakeholder Partnership and Collaboration',
            'items' => [
                'Conduct of research on pertinent rules, regulations, and organizational mandates',
                'Conduct of joint-meetings with key stakeholders',
                'Development of partnership documents such as Memorandum of Agreements and Terms of Reference',
                'Development of policies, guidelines, and procedures for partnership building and accreditation',
                'Conduct of monitoring and evaluation on the status of partnerships',
            ],
        ],
        [
            'domain' => 'Real-Time Hazard and Risk Assessment',
            'items' => [
                'Conduct of Pre-Disaster Risk Assessment (PDRA)',
                'Utilization of tools for PDRA',
            ],
        ],
        [
            'domain' => 'Rapid Disaster Damage and Needs Assessment',
            'items' => [
                'Conduct of Rapid Damage Assessment and Needs Analysis',
                'Conduct of data gathering such as direct observation, interviews, and focused group discussion',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with the Emergency Operations Center in charge',
            ],
        ],
        [
            'domain' => 'Emergency Operations Center (EOC) Coordination and Reporting',
            'items' => [
                'Management and operationalization of OpCen/EOC',
                'Development of press releases and handling media concerns',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with other Response Clusters',
                'Organizing meetings at the EOC',
            ],
        ],
        [
            'domain' => 'Incident Command and Emergency Leadership',
            'items' => [
                'Delegation of authority and priorities for tactical response',
                'Development of incident objectives',
                'Establishment of linkage with other stakeholders',
                'Preparation and release of media reports and press statements',
                'Establishment of safety protocols',
                'Implementation of strategies and tactics based on objectives',
                'Development of incident action plans, tactical reports, and other relevant documents',
                'Management and tracking of resources',
                'Establishment, maintenance, and repair of facilities for tactical response',
                'Management of financial and administrative concerns for the tactical response',
                'Coordination of actions with the Response Clusters',
            ],
        ],
        [
            'domain' => 'Early Warning Dissemination',
            'items' => [
                'Identification of safe, secure, and accessible sites for camps',
                'Development of reports on situation updates and actions taken on the dissemination of warnings and evacuation orders',
                'Establishment, repair, and maintenance of tools and equipment used in dissemination of warnings and evacuation orders',
                'Management of financial and administrative concerns for the dissemination of warnings and evacuation orders',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Emergency Telecommunications and Network Restoration',
            'items' => [
                'Deployment at disaster-stricken sites to restore emergency telecommunications',
                'Development of reports on situation updates and actions taken on the restoration of emergency telecommunications',
                'Establishment, repair, and maintenance of facilities and equipment used in the restoration of emergency telecommunications',
                'Management of financial and administrative concerns for the restoration of emergency telecommunications',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Food and Non-Food Relief Distribution',
            'items' => [
                'Inspection and assessment of food and non-food items in accordance to agreed standards',
                'Monitoring of inventory of food and non-food items',
                'Stockpiling and warehousing of food and non-food items',
                'Deployment of disaster-stricken sites to distribute food and non-food items',
                'Development of reports on situation updates and actions taken on the distribution of food and non-food items',
                'Establishment, repair, and maintenance of facilities and equipment used in the distribution of food and non-food items',
                'Management of financial and administrative concerns for the distribution of food and non-food items',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Management of Internally Displaced Persons (IDPs)',
            'items' => [
                'Identification of safe, secure, and accessible sites for camps',
                'Deployment at disaster-stricken sites to organize camp management activities',
                'Coordination with relevant stakeholders to address camp management issues',
                'Maintenance on the listing and profiling of affected communities',
                'Provision of mental health and psychosocial support services',
                'Development of reports on situation updates and actions taken on the management of camps',
                'Establishment, repair, and maintenance of facilities and equipment used in the management of camps',
                'Management of financial and administrative concerns for the management of camps',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Protection of Internally Displaced Persons (IDPs)',
            'items' => [
                'Deployment at disaster-stricken sites to provide protection services for the internally displaced population',
                'Conduct of data gathering and investigation about protection issues',
                'Development of reports on situation updates and actions taken on the provision of protection services for the internally displaced population',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of protection services for the internally displaced population',
                'Management of financial and administrative concerns on the provision of protection services for the internally displaced population',
                'Coordination of actions with Emergency Operations Center',
            ],
        ],
        [
            'domain' => 'Emergency Security and Public Safety Management',
            'items' => [
                'Deployment at disaster-stricken sites to maintain law and order',
                'Conduct of data gathering and investigation needed for the maintenance of law and order',
                'Conduct of traffic management',
                'Conduct of crowd control',
                'Provision of security services to escort operating teams',
                'Coordination with Crisis Management Committees to address concerns on human-induced crises',
                'Development of reports on situation updated and actions on the maintenance of law and order',
                'Establishment, repair, and maintenance of facilities and equipment used in the maintenance of law and order',
                'Management of financial and administrative concerns for the maintenance of law and order',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Education in Emergencies',
            'items' => [
                'Deployment at disaster-stricken sites to provide continuing education',
                'Provision of mental health and psychosocial support services',
                'Administering of a wide range of techniques for continuing education',
                'Development of reports on situation updates and actions on the provision of continuing education',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of continuing education',
                'Management of financial and administrative concerns for the provision of continuing education',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Emergency Health, Water, and Sanitation (WASH) Services',
            'items' => [
                'Provision of first standard and basic life support services',
                'Establishment and management of triage',
                'Establishment and management of referral system',
                'Provision of minimum initial service package for reproductive health',
                'Provision of mental health and psychosocial support service',
                'Administration of protocols for water sanitation, and hygiene',
                'Provision of a wide range of hospital-based services',
                'Management of mass casualties',
                'Development of reports on situation updates and actions on the provision of health services',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of health services',
                'Management of financial and administrative concerns for the provision of health services',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Search, Rescue, and Retrieval Operations',
            'items' => [
                'Provision of initial rescue as first responders',
                'Deployment at disaster-stricken sites to provide search, rescue, retrieval services',
                'Management of response for chemical, biological, radiological, nuclear, and explosives',
                'Coordination with Crisis Management Committees to ensure the safety of the rescue sites from lawless elements',
                'Development of reports on situation updated and actions on the provision of search, rescue, and retrieval services',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of search, rescue, and retrieval services',
                'Management of financial and administrative concerns for the provision of search, rescue, and retrieval services',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Center',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Management of the Dead and Missing Persons',
            'items' => [
                'Processing of human remains from the search and recovery operation',
                'Facilitation of requirements for disaster victim identification',
                'Facilitation of final arrangements for the dead',
                'Facilitation of arrangements with funeral parlors',
                'Facilitation of arrangements with LGU leagues, cemetery, and other religious organization for burial',
                'Provision of psychosocial services for the bereaved families',
                'Management and maintenance of records for the dead and missing',
                'Development of reports on situation updates and actions on the provision of services and management of the dead and missing',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of services related to management of the dead and missing',
                'Management of financial and administrative concerns for the provision of services related to the management of the dead and missing',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Emergency Logistics and Lifeline Restoration',
            'items' => [
                'Provision of augmentation for transportation services',
                'Provision of augmentation for supplies and equipment',
                'Inspection of logistical resources',
                'Warehousing and stockpiling of logistical resources',
                'Coordination with key stakeholders to ensure continuity of supplies',
                'Conduct of debris clearing operations',
                'Restoration of critical lifelines and facilities',
                'Management and maintenance of records for logistical concerns',
                'Development of reports on situation updates and actions on the provision of services management of the dead and missing',
                'Establishment, repair, and maintenance of facilities and equipment used in the provision of services related to management of the dead and missing',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Centers',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'International Humanitarian Assistance Coordination',
            'items' => [
                'Analysis of macro-needs that need international assistance based on latest situation updates',
                'Establishment of communication with international partners',
                'Processing of documents based on international and national guidelines and protocols',
                'Development of reports on situation updates and actions on the coordination with international partners',
                'Management of hubs and facilities used in coordination with international partners',
                'Maintenance and repair of facilities and equipment used in coordination with international partners',
                'Management of financial and administrative concerns for the coordination with international partners',
                'Coordination of actions with the Incident Management Team in charge',
                'Coordination of actions with Emergency Operations Center',
                'Coordination of actions with other Response Clusters',
            ],
        ],
        [
            'domain' => 'Post-Disaster Needs Assessment',
            'items' => [
                'Development of policies and guidelines on Post-Disaster Needs Assessment',
                'Management of financial and administrative concerns for the conduct of Post-Disaster Needs Assessment',
                'Conduct of data gathering such as direct observation, interviews, and focused group discussion',
                'Utilization of tools for Post-Disaster Needs Assessment',
                'Analysis and interpretation of Post-Disaster Needs Assessment findings',
                'Development of reports for Post-Disaster Needs Assessment',
                'Monitoring of projects implemented based on the Post-Disaster Needs Assessment report',
            ],
        ],
        [
            'domain' => 'Post-Disaster Comprehensive Risk and Impact',
            'items' => [
                'Demographic assessment',
                'Hazard assessment',
                'Vulnerability assessment',
                'Risk assessment',
                'Capacity assessment',
                'Documentation of the post-disaster situation',
                'Documentation and review of disaster scenarios and models',
                'Map development and review',
                'Review of risk assessment tools',
                'Analysis of damages and losses incurred',
            ],
        ],
        [
            'domain' => 'Build Back Better Program Development and Implementation',
            'items' => [
                'Environmental scanning',
                'Land use planning',
                'Development planning',
                'Budgeting and programming of activities for Disaster Risk Reduction and Management and/or Climate Change Adaptation and Mitigation',
                'Conduct of research on Disaster Risk Reduction and Management and/or Climate Change Adaptation and Mitigation',
                'Conduct of monitoring and evaluation of program results',
                'Review and updating of program results',
                'Review and updating of plans, policies, guidelines, and protocols',
            ],
        ],
        [
            'domain' => 'Disaster-Resilient Infrastructure Rehabilitation and Recovery',
            'items' => [
                'Development of designs and standards for building resilient facilities, infrastructures, transportation systems, and other disaster control measures',
                'Construction of facilities, infrastructures, transportation systems, and other disaster control measures',
                'Maintenance of facilities, infrastructures, transportation systems, and other disaster control measures',
                'Assessment and inspections of facilities, infrastructures, transportation systems, and other disaster control measures',
                'Conduct of monitoring of compliance of stakeholders on agreed designs and standards',
            ],
        ],
        [
            'domain' => 'Livelihood Restoration and Social Recovery Programs',
            'items' => [
                'Conduct of research and feasibility studies',
                'Conduct of capacity building activities on livelihood programs',
                'Delivery of social services for the affected communities',
                'Monitoring and evaluation of the results of implementation of livelihood programs and other social services',
            ],
        ],
    ],

    'open_questions' => [
        'What DRRM-related knowledge or skills would you like to develop to better perform your role?',
        'What DRRM-related responsibilities or coordination functions do you find most challenging due to gaps in your knowledge, skills, or experience?',
        'What new DRRM knowledge or skills do you need to effectively carry out your upcoming council responsibilities, programs, or initiatives?',
        'What DRRM training topics would be most beneficial in strengthening your role?',
        'Based on your recent DRRM coordination or emergency response experience, what competencies should be strengthened among National & Regional DRRM Council members?',
    ],

];
